/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004491",
        "on-tertiary-fixed-variant": "#454748",
        "on-secondary-fixed": "#002106",
        "inverse-primary": "#acc7ff",
        "surface-container-low": "#f1f4f9",
        "on-surface-variant": "#424752",
        "primary-container": "#0056b3",
        "on-tertiary-container": "#ced0d1",
        "on-secondary-fixed-variant": "#00531a",
        "surface-bright": "#f7f9ff",
        "secondary-fixed": "#83fc8e",
        "inverse-on-surface": "#eef1f6",
        "background": "#f7f9ff",
        "outline-variant": "#c2c6d4",
        "tertiary-fixed": "#e1e3e4",
        "on-surface": "#181c20",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e5e8ee",
        "on-tertiary-fixed": "#191c1d",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-tint": "#115cb9",
        "surface-container": "#ebeef3",
        "secondary-fixed-dim": "#66df75",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e8",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#acc7ff",
        "tertiary": "#3f4243",
        "on-primary-fixed": "#001a40",
        "error-container": "#ffdad6",
        "on-primary-container": "#bbd0ff",
        "outline": "#727784",
        "on-primary": "#ffffff",
        "secondary": "#006e25",
        "on-background": "#181c20",
        "surface-container-highest": "#e0e3e8",
        "primary-fixed": "#d7e2ff",
        "tertiary-container": "#57595a",
        "secondary-container": "#80f98b",
        "primary": "#003f87",
        "on-secondary-container": "#007327",
        "surface-dim": "#d7dadf",
        "inverse-surface": "#2d3135"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "touch-target-min": "48px",
        "stack-lg": "48px",
        "unit": "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "margin-mobile": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-lg": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["26px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
